#!/usr/bin/sh
#  Customize to your needs...
# Basic path

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/texbin:/Users/john/Projects/local/bin"

if [[ -d "$HOME/perl5/perlbrew/bin" ]]; then
  export PATH="/Users/john/perl5/perlbrew/bin:/Users/john/perl5/perlbrew/perls/perl-5.14.2/bin:$PATH"
fi

# PKG_CONFIG
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig/:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH"

# Python Path
export PYTHONPATH="/Users/harjohn/Perforce/lib/python:/usr/local/lib/python:/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

# RVM Path
if [[ -d $HOME/.rvm/bin ]]; then
  export PATH=$PATH:$HOME/.rvm/bin
fi
